export const mock = [
  {
    tags: [],
    width: 2016,
    datetime: 1518753106,
    account_url: null,
    link: 'https://i.imgur.com/TKQPXk2.jpg',
    type: 'image/jpeg',
    favorite: false,
    ups: null,
    in_most_viral: false,
    vote: null,
    animated: false,
    size: 742388,
    description: null,
    title: 'Chapel on the Rock, Colorado [2016x1512][OC]',
    comment_count: null,
    has_sound: false,
    in_gallery: false,
    favorite_count: null,
    bandwidth: 24139488208,
    nsfw: false,
    section: 'EarthPorn',
    downs: null,
    ad_url: '',
    id: 'TKQPXk2',
    account_id: null,
    ad_type: 0,
    points: null,
    height: 1512,
    is_album: false,
    views: 32516,
    is_ad: false,
    score: 30523
  },
  {
    downs: null,
    section: 'EarthPorn',
    nsfw: false,
    ad_url: '',
    id: 'q2uohuJ',
    account_id: null,
    ad_type: 0,
    height: 2808,
    points: null,
    is_ad: false,
    score: 57419,
    is_album: false,
    views: 270260,
    description: null,
    size: 906798,
    title: 'Mt Seymour, Vancouver BC Canada 3264x2448 [OC]',
    in_gallery: false,
    comment_count: null,
    has_sound: false,
    bandwidth: 245071227480,
    favorite_count: null,
    favorite: false,
    ups: null,
    animated: false,
    in_most_viral: false,
    vote: null,
    account_url: null,
    link: 'https://i.imgur.com/q2uohuJ.jpg',
    tags: [],
    width: 2808,
    datetime: 1518751204,
    type: 'image/jpeg'
  },
  {
    title: 'Cane River, Natchitoches, La. [OC] [3929 x 2947]',
    description: null,
    size: 559547,
    bandwidth: 148654291943,
    favorite_count: null,
    in_gallery: false,
    comment_count: null,
    has_sound: false,
    ad_url: '',
    id: 'pprl8Dk',
    account_id: null,
    downs: null,
    section: 'EarthPorn',
    nsfw: false,
    is_ad: false,
    score: 263717,
    views: 265669,
    is_album: false,
    ad_type: 0,
    height: 2304,
    points: null,
    account_url: null,
    link: 'https://i.imgur.com/pprl8Dk.jpg',
    tags: [],
    width: 3072,
    datetime: 1518750003,
    type: 'image/jpeg',
    favorite: false,
    animated: false,
    in_most_viral: false,
    vote: null,
    ups: null
  },
  {
    type: 'image/jpeg',
    link: 'https://i.imgur.com/KMebpmj.jpg',
    account_url: null,
    width: 3024,
    datetime: 1518742804,
    tags: [],
    animated: false,
    vote: null,
    in_most_viral: false,
    ups: null,
    favorite: false,
    bandwidth: 892871455169,
    favorite_count: null,
    in_gallery: false,
    has_sound: false,
    comment_count: null,
    title: 'Zion National Park [OC] 3024x4032',
    description: null,
    size: 4024681,
    score: 188833,
    is_ad: false,
    views: 221849,
    is_album: false,
    points: null,
    height: 4032,
    ad_type: 0,
    account_id: null,
    id: 'KMebpmj',
    ad_url: '',
    downs: null,
    nsfw: false,
    section: 'EarthPorn'
  },
  {
    title: 'Sunset, Neil Island, Andaman and Nicobar Islands,[OC] 3264x2448',
    size: 800896,
    description: null,
    favorite_count: null,
    bandwidth: 653994053888,
    comment_count: null,
    has_sound: false,
    in_gallery: false,
    id: '0XeEmtO',
    ad_url: '',
    account_id: null,
    section: 'EarthPorn',
    nsfw: false,
    downs: null,
    views: 816578,
    is_album: false,
    is_ad: false,
    score: 121768,
    ad_type: 0,
    height: 2448,
    points: null,
    tags: [],
    datetime: 1518715803,
    width: 3264,
    account_url: null,
    link: 'https://i.imgur.com/0XeEmtO.jpg',
    type: 'image/jpeg',
    favorite: false,
    in_most_viral: false,
    vote: null,
    animated: false,
    ups: null
  },
  {
    is_album: false,
    views: 23596,
    score: 19775,
    is_ad: false,
    points: null,
    height: 5304,
    ad_type: 0,
    account_id: null,
    id: 'N170Iao',
    ad_url: '',
    section: 'EarthPorn',
    nsfw: false,
    downs: null,
    favorite_count: null,
    bandwidth: 94897000636,
    has_sound: false,
    comment_count: null,
    in_gallery: false,
    title: 'Buena Vista, Colorado (OC) [7952 x 5304]',
    size: 4021741,
    description: null,
    vote: null,
    in_most_viral: false,
    animated: false,
    ups: null,
    favorite: false,
    type: 'image/jpeg',
    datetime: 1518655835,
    width: 7952,
    tags: [],
    link: 'https://i.imgur.com/N170Iao.jpg',
    account_url: null
  },
  {
    is_album: false,
    views: 425538,
    is_ad: false,
    score: 112105,
    ad_type: 0,
    height: 1080,
    points: null,
    id: 'iCtomjC',
    ad_url: '',
    account_id: null,
    nsfw: false,
    section: 'EarthPorn',
    downs: null,
    favorite_count: null,
    bandwidth: 170056899864,
    comment_count: null,
    has_sound: false,
    in_gallery: false,
    title:
      "Today is Oregon's birthday. Here is a picture of her misty mountain foothills. [OC][1620x1080]",
    size: 399628,
    description: null,
    in_most_viral: false,
    vote: null,
    animated: false,
    ups: null,
    favorite: false,
    type: 'image/jpeg',
    tags: [],
    datetime: 1518625803,
    width: 1620,
    account_url: null,
    link: 'https://i.imgur.com/iCtomjC.jpg'
  },
  {
    size: 331735,
    description: null,
    title:
      'Icelandic landscape - June 2017. Taken on a trip North of Reykjavik [OC][4032x3024]',
    has_sound: false,
    comment_count: null,
    in_gallery: false,
    favorite_count: null,
    bandwidth: 58428485550,
    section: 'EarthPorn',
    nsfw: false,
    downs: null,
    account_id: null,
    ad_url: '',
    id: 'a4G2gFu',
    points: null,
    height: 1704,
    ad_type: 0,
    is_album: false,
    views: 176130,
    score: 161456,
    is_ad: false,
    width: 2272,
    datetime: 1518603003,
    tags: [],
    link: 'https://i.imgur.com/a4G2gFu.jpg',
    account_url: null,
    type: 'image/jpeg',
    favorite: false,
    ups: null,
    vote: null,
    in_most_viral: false,
    animated: false
  },
  {
    title: 'Arambol beach, Goa. [OC] [4160X3120]',
    size: 423902,
    description: null,
    favorite_count: null,
    bandwidth: 466094661668,
    comment_count: null,
    has_sound: false,
    in_gallery: false,
    id: 'dyln4by',
    ad_url: '',
    account_id: null,
    nsfw: false,
    section: 'EarthPorn',
    downs: null,
    views: 1099534,
    is_album: false,
    is_ad: false,
    score: 468883,
    ad_type: 0,
    points: null,
    height: 3120,
    tags: [],
    datetime: 1518591603,
    width: 4160,
    account_url: null,
    link: 'https://i.imgur.com/dyln4by.jpg',
    type: 'image/jpeg',
    favorite: false,
    in_most_viral: false,
    vote: null,
    animated: false,
    ups: null
  },
  {
    type: 'image/jpeg',
    account_url: null,
    link: 'https://i.imgur.com/DUZVPZV.jpg',
    tags: [],
    datetime: 1518572403,
    width: 1920,
    animated: false,
    in_most_viral: false,
    vote: null,
    ups: null,
    favorite: false,
    bandwidth: 56212585232,
    favorite_count: null,
    in_gallery: false,
    comment_count: null,
    has_sound: false,
    title: '[OC]Avalanche Lake, Montana, USA[1920x1442]',
    description:
      'Details:\n\nShot with Panasonic GH3\n20mm Panasonic Lumix lens\nf/1.7, 1/400 sec., 125 ISO\n1920 x 1442\nSaturation, contrast, vibrancy boosts, and sharpening performed in Paintshop Pro x9\n\nEDIT: Unedited version: https://imgur.com/gallery/7d7qKp4',
    size: 693332,
    is_ad: false,
    score: 65475,
    views: 81076,
    is_album: false,
    ad_type: 0,
    height: 1442,
    points: null,
    id: 'DUZVPZV',
    ad_url: '',
    account_id: null,
    downs: null,
    section: 'EarthPorn',
    nsfw: false
  },
  {
    favorite: false,
    vote: null,
    in_most_viral: false,
    animated: false,
    ups: null,
    datetime: 1518544203,
    width: 1920,
    tags: [],
    link: 'https://i.imgur.com/ECzq95K.jpg',
    account_url: null,
    type: 'image/jpeg',
    account_id: null,
    ad_url: '',
    id: 'ECzq95K',
    nsfw: false,
    section: 'EarthPorn',
    downs: null,
    views: 48980,
    is_album: false,
    score: 40670,
    is_ad: false,
    points: null,
    height: 1080,
    ad_type: 0,
    title: 'A starry sunrise [1920x1080] [OC]',
    size: 249355,
    description: null,
    favorite_count: null,
    bandwidth: 12213407900,
    has_sound: false,
    comment_count: null,
    in_gallery: false
  }
]
